{
 "title": "PeerTube OpenTelemetry",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(up{service=\"peertube-server-metrics\"}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peertube_users_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "{{videoOrigin}}"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peertube_channels_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "{{videoOrigin}}"
    }
   ]
  },
  {
   "title": "Videos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(peertube_videos_total{service=\"$service\", namespace=\"$namespace\"})",
     "legendFormat": "Views by local users"
    }
   ]
  },
  {
   "title": "Video views",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peertube_video_views_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Views by local users"
    }
   ]
  },
  {
   "title": "Video size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peertube_video_bytes_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "{{videoOrigin}}"
    }
   ]
  },
  {
   "title": "Playlists",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peertube_playlists_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Local playlists"
    }
   ]
  },
  {
   "title": "Comments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peertube_comments_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Total comments by local users"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "peertube_users_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Total users"
    },
    {
     "expr": "peertube_active_users_total{activeInterval=\"monthly\", service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Active {{activeInterval}}"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "peertube_channels_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Total local channels"
    },
    {
     "expr": "peertube_active_channels_total{activeInterval=\"weekly\", service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Active {{activeInterval}}"
    }
   ]
  },
  {
   "title": "Videos",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "peertube_videos_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "{{videoOrigin}}"
    }
   ]
  },
  {
   "title": "Instance follows",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "peertube_instance_followers_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Followers"
    },
    {
     "expr": "peertube_instance_following_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Following"
    }
   ]
  },
  {
   "title": "Viewers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "peertube_viewers_total{service=\"$service\", videoOrigin=\"local\", viewerOrigin=\"local\", namespace=\"$namespace\"}",
     "legendFormat": "Local video - Local viewer"
    },
    {
     "expr": "peertube_viewers_total{service=\"$service\", videoOrigin=\"remote\", viewerOrigin=\"local\", namespace=\"$namespace\"}",
     "legendFormat": "Remote Video - Local Viewer"
    },
    {
     "expr": "peertube_viewers_total{service=\"$service\", videoOrigin=\"local\", viewerOrigin=\"remote\", namespace=\"$namespace\"}",
     "legendFormat": "Local Video - Remote Viewer"
    }
   ]
  },
  {
   "title": "Lives",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "peertube_running_lives_total{service=\"$service\", liveOrigin=\"local\", namespace=\"$namespace\"}",
     "legendFormat": "Local"
    },
    {
     "expr": "peertube_running_lives_total{service=\"$service\", liveOrigin=\"remote\", namespace=\"$namespace\"}",
     "legendFormat": "Remote"
    }
   ]
  },
  { "title": "Player metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Playback errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(playerMode, videoOrigin) (peertube_playback_errors_count_total{service=\"$service\", namespace=\"$namespace\"} - peertube_playback_errors_count_total{service=\"$service\", instance=\"$instance\"} offset $__interval)",
     "legendFormat": "{{playerMode}} - {{ videoOrigin }}"
    }
   ]
  },
  {
   "title": "Resolutions changes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(playerMode, videoOrigin) (peertube_playback_resolution_changes_count_total{service=\"$service\", namespace=\"$namespace\"} - peertube_playback_resolution_changes_count_total{service=\"$service\", instance=\"$instance\"} offset $__interval)",
     "legendFormat": "{{playerMode}} -  {{videoOrigin}}"
    }
   ]
  },
  {
   "title": "Player network - Local videos",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (peertube_playback_http_downloaded_bytes_total{service=\"$service\", videoOrigin=\"local\", namespace=\"$namespace\"} - peertube_playback_http_downloaded_bytes_total{service=\"$service\", videoOrigin=\"local\", instance=\"$instance\"} offset $__interval)",
     "legendFormat": "HTTP downloaded"
    },
    {
     "expr": "sum(peertube_playback_p2p_downloaded_bytes_total{service=\"$service\", videoOrigin=\"local\", namespace=\"$namespace\"} - peertube_playback_p2p_downloaded_bytes_total{service=\"$service\",  videoOrigin=\"local\", instance=\"$instance\"} offset $__interval)",
     "legendFormat": "P2P downloaded"
    },
    {
     "expr": "sum(peertube_playback_p2p_uploaded_bytes_total{service=\"$service\", videoOrigin=\"local\", namespace=\"$namespace\"} - peertube_playback_p2p_uploaded_bytes_total{service=\"$service\", videoOrigin=\"local\", instance=\"$instance\"} offset $__interval)",
     "legendFormat": "P2P uploaded"
    }
   ]
  },
  {
   "title": "Player network - Remote videos",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(peertube_playback_http_downloaded_bytes_total{service=\"$service\", videoOrigin=\"remote\", namespace=\"$namespace\"} - peertube_playback_http_downloaded_bytes_total{service=\"$service\", videoOrigin=\"remote\", instance=\"$instance\"} offset $__interval)",
     "legendFormat": "HTTP downloaded"
    },
    {
     "expr": "sum(peertube_playback_p2p_downloaded_bytes_total{service=\"$service\", videoOrigin=\"remote\", namespace=\"$namespace\"} - peertube_playback_p2p_downloaded_bytes_total{service=\"$service\", videoOrigin=\"remote\", instance=\"$instance\"} offset $__interval)",
     "legendFormat": "P2P downloaded"
    },
    {
     "expr": "sum(peertube_playback_p2p_uploaded_bytes_total{service=\"$service\", videoOrigin=\"remote\", namespace=\"$namespace\"} - peertube_playback_p2p_uploaded_bytes_total{service=\"$service\", videoOrigin=\"remote\", instance=\"$instance\"} offset $__interval)",
     "legendFormat": "P2P uploaded"
    }
   ]
  },
  { "title": "System Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_system_seconds_total{service=\"$service\", namespace=\"$namespace\"}[$__rate_interval]) * 100",
     "legendFormat": "PeerTube system"
    },
    {
     "expr": "irate(process_cpu_user_seconds_total{service=\"$service\", namespace=\"$namespace\"}[$__rate_interval]) * 100",
     "legendFormat": "PeerTube User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"node\", namespace=\"$namespace\", mode!=\"idle\"}[$__rate_interval]) * 100)",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_memory_usage_bytes{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "PeerTube {{memoryType}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{namespace=\"$namespace\", job=\"node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_Active_bytes{namespace=\"$namespace\", job=\"node\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Opened Files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "PeerTube opened files"
    },
    {
     "expr": "node_filefd_allocated{job=\"node\", namespace=\"$namespace\"}",
     "legendFormat": "Total opened files"
    },
    {
     "expr": "node_filefd_maximum{job=\"node\", namespace=\"$namespace\"}",
     "legendFormat": "Max total opened files"
    }
   ]
  },
  { "title": "PeerTube monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Event loop lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nodejs_eventloop_lag_seconds{service=\"$service\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Garbage collector",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nodejs_gc_duration_seconds_bucket{service=\"$service\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "95th percentile"
    }
   ]
  },
  {
   "title": "Active handles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Libuv active resources",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodejs_active_resources_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Libuv active requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodejs_active_requests_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Waiting Job Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "peertube_job_queue_total{state=\"waiting\", service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "{{jobType}}"
    }
   ]
  },
  {
   "title": "Processing Job Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "peertube_job_queue_total{state=\"active\", jobType!=\"videos-views-stats\", service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "{{jobType}}"
    }
   ]
  },
  {
   "title": "AP inbox waiting",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "peertube_ap_inbox_waiting_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Total waiting"
    }
   ]
  },
  {
   "title": "AP inbox processed success",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(peertube_ap_inbox_success_total{service=\"$service\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{activityType}}"
    }
   ]
  },
  {
   "title": "AP inbox processed errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(peertube_ap_inbox_error_total{service=\"$service\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{activityType}}"
    }
   ]
  },
  {
   "title": "Redundancy used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "peertube_redundancy_used_bytes_total{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "{{strategy}}"
    }
   ]
  }
 ]
}