{{- if and (not .Values.server.config.admin.existingSecret) (.Values.server.config.admin.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "peertube.server.name" . }}-admin
  namespace: {{ template "peertube.namespace" . }}
  labels:
    {{- include "peertube.server.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.server.config.admin.password | quote }}
{{- end }}
{{- if and (not .Values.server.externalRedis.existingSecret) (.Values.server.externalRedis.password) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "peertube.server.name" . }}-redis
  namespace: {{ template "peertube.namespace" . }}
  labels:
    {{- include "peertube.server.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.server.externalRedis.password | quote }}
{{- end }}
{{- if and (not .Values.server.externalPostgres.existingSecret) .Values.server.externalPostgres.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "peertube.server.name" . }}-postgres
  namespace: {{ template "peertube.namespace" . }}
  labels:
    {{- include "peertube.server.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-username: {{ default "default" .Values.server.externalPostgres.username | quote }}
  postgres-password: {{ .Values.server.externalPostgres.password | quote }}
{{- end }}
{{- if and (not .Values.server.config.secrets.existingSecret) .Values.server.config.secrets.peertube }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "peertube.server.name" . }}-peertube-secret
  namespace: {{ template "peertube.namespace" . }}
  labels:
    {{- include "peertube.server.labels" . | nindent 4 }}
type: Opaque
stringData:
  peertube-secret: {{ .Values.server.config.secrets.peertube | quote }}
{{- end }}