{{- if .Values.runner.enabled -}}
{{- if .Values.runner.vpa.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "peertube.runner.name" . }}
  namespace: {{ template "peertube.namespace" . }}
  labels:
  {{- include "peertube.runner.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: {{ template "peertube.runner.name" . }}
  updatePolicy:
    updateMode: {{ .Values.runner.vpa.updateMode }}
  resourcePolicy:
    containerPolicies:
    - containerName: {{ template "peertube.runner.name" . }}
    {{ with .Values.runner.vpa.containerPolicy }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}